---
- include_tasks: nagios-centos7.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '7' and nagios_packages

- include_tasks: nagios-ubuntu.yml
  when: ansible_distribution == "Ubuntu" and nagios_packages

- include_tasks: nagios-source.yml
  when: not nagios_packages
