- name: Install apache, nagios-core, nagios-plugins
  apt:
    name:
      - apache2
      - bind9-utils
      - gettext
      - nagios-images
      - nagios-plugins-contrib
      - nagios4
      - nagios4-cgi
      - nagios4-common
      - nagios4-core
      - nmap
      - python3-passlib
      - wget
      - which
      - unzip
      - vim
      - zip
    state: present
  tags:
    - install

## nagios configuration
- name: set shell for user nagios
  user:
    name: nagios
    group: nagios
    shell: '/bin/bash'
    home: '/var/lib/nagios'
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    create_home: yes
    state: present

- name: copy nagios.cfg template
  template:
    src: 'nagios.cfg.j2'
    dest: '/etc/nagios4/nagios.cfg'

## apache2 configuration
- name: copy apache2.conf nagios config
  copy:
    src: 'apache2-nagios.conf'
    dest: '/etc/nagios4/apache2.conf'

- name: copy nagios.cfg template
  template:
    src: 'nagios.cfg.j2'
    dest: '/etc/nagios4/nagios.cfg'

- name: enable modules in apache
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - authz_groupfile
    - auth_digest
    - rewrite
    - cgi
  notify: nagios apache2 restart
  ignore_errors: "{{ ansible_check_mode }}"

- name: set apache nagiosadmin pass
  community.general.htpasswd:
    path: '/etc/nagios4/htdigest.users'
    name: '{{ nagios_adminuser }}'
    password: '{{ nagios_adminpass }}'
    owner: nagios
    group: www-data
    mode: 0640
    crypt_scheme: md5_crypt

- name: Ensure nagios has selected state and enabled on boot.
  service:
    name: nagios
    state: started
    enabled: true
