- name: Install some packages
  dnf:
    name:
      - epel-release
      - bind-utils
      - gcc
      - gd
      - gd-devel
      - gettext
      - glibc
      - glibc-common
      - wget
      - which
      - unzip
      - vim
      - zip
    state: present

- name: update operating system
  dnf:
    name: '*'
    state: latest

- name: Install apache, nagios-core, nagios-plugins, nrpe
  dnf:
    name:
      - httpd
      - mailx
      - mod_ssl
      - nagios
      - nagios-common
      - nagios-contrib
      - nagios-devel
      - nagios-plugins
      - nagios-plugins-*
      - nmap
      - nrpe
      - postfix
      - openssl-libs
      - python3-passlib
    state: present
    enablerepo: 'powertools,epel'

- include: conf-httpd.yml

- name: set http nagiosadmin pass
  community.general.htpasswd:
    path: '/etc/nagios/passwd'
    name: '{{ nagios_adminuser }}'
    password: '{{ nagios_adminpass }}'
    owner: root
    group: apache
    mode: 0640
    crypt_scheme: md5_crypt

- name: Ensure nagios has selected state and enabled on boot.
  service:
    name: nagios
    state: started
    enabled: true
