---
- name: restart httpd
  service:
    name: httpd
    state: restarted

- name: restart apache2
  service:
    name: apache2
    state: restarted

- name: restart mysql
  service: 
    name: mariadb
    state: restarted
    sleep: 5

- name: restart nagios
  service:
    name: nagios
    state: restarted
  